version: '3.1'

services:
    
    web-server:
        image: webdev89/phpdebian
        restart: always
        ports:
          - 8211:80
        environment:
            DB_HOST: db
            DB_DB: wordpress
            DB_USER: wordpress
            DB_PASS: wordpress
            TZ: Europe/Minsk
        volumes:
          - ./virtualhost/:/etc/apache2/sites-enabled/
          - ./site/:/var/www/html
        depends_on:
          - db
        networks:
          - wordpress_network
          
    db:
        image: mysql:5.7
        restart: always
        ports:
          - 8212:3306
        environment:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress 
          MYSQL_PASSWORD: wordpress
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./databases/:/docker-entrypoint-initdb.d
          - wordpress:/var/lib/mysql
        networks:
          - wordpress_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: 
          - 8213:80
        environment:
          PMA_HOST: db
        depends_on:
          - db
        networks:
          - wordpress_network
          
networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress: